eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost


microservice:
  payment-service:
          endpoints:
            endoint:
                  uri: http://PAYMENT-SERVICE/payments/doPayment
   
  order-service:
          endpoints:
            endoint:
                  uri: http://ORDER-SERVICE/orders/bookOrder 
                  
